DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	login VARCHAR(255) NOT NULL,
	password VARCHAR (255) NOT NULL,
	email VARCHAR (255) NOT NULL,
	created_on TIMESTAMP NOT NULL,
	verified BOOLEAN DEFAULT FALSE,
	last_login TIMESTAMP,
	deleted BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role (
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (user_id, role_id),
	FOREIGN KEY (user_id) REFERENCES users (id),
	FOREIGN KEY (role_id) REFERENCES roles (id)
);

DROP TABLE IF EXISTS rooms;
CREATE TABLE rooms (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
	id SERIAL PRIMARY KEY,
	content VARCHAR(255) NOT NULL,
	author_id INT NOT NULL,
	room_id INT NOT NULL,
	created_at TIMESTAMP,
	FOREIGN KEY (author_id) REFERENCES users (id),
	FOREIGN KEY (room_id) REFERENCES rooms (id)
);

DROP TABLE IF EXISTS tokens;
CREATE TABLE tokens (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	value VARCHAR(255) NOT NULL,
	expiry TIMESTAMP NOT NULL,
	user_id INT NULL
);

INSERT INTO roles (name) 
VALUES ('USER'), ('VERIFIED'), ('ADMIN'), ('OWNER');

INSERT INTO rooms (name) 
VALUES ('General');